{{- if .Values.ingress.enabled -}}
{{- if semverCompare "<1.14-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: extensions/v1beta1
{{- else if semverCompare "<1.19-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: networking.k8s.io/v1
{{- end }}
kind: Ingress
metadata:
  {{- if .Values.ingress.annotations }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ tpl $value $ | quote }}
    {{- end }}
  {{- end}}
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    release: "{{ .Chart.Name }}"
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
{{- if semverCompare "<1.19-0" .Capabilities.KubeVersion.GitVersion }}
      - backend:
          serviceName: {{ .Chart.Name }}
          servicePort: 8080
{{- else }}
      - backend:
          service:
            name: {{ .Chart.Name }}
            port:
              number: 8080
        pathType: ImplementationSpecific
{{- end }}
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.secretName }}
{{- end }}
